### ISSUE TITLE
Doubts about the project

### ISSUE THREAD

**Issue by brunobandev** [fariasmateuss/tindev#41]
Hey man, I was looking at your project and trying to install it on my pc.
Is this project finished or you have a backlog for it?

**Comment by fariasmateuss** [comment]
Hi, @brunobandev!

First, I would like to apologize for the delay, I was away for a while, and I'm coming back now...

At the moment I don't have any backlog, but yes, some ideas.

Feel free to send your PR

**Comment by brunobandev** [comment]
Are you open to new project?

**Comment by fariasmateuss** [comment]
Yep!  I’m looking to collaborate on open source projects 🤩

**Comment by brunobandev** [comment]
I'm starting a project, but I need someone to work in the frontend, would you like to know if you have interesting in know more about it?

**Comment by fariasmateuss** [comment]
Sure! Send me a message on telegram @fariasmateuss
