### ISSUE TITLE
Fresh backend bug, maybe mongodb

### ISSUE THREAD

**Issue by franciscof5** [fariasmateuss/tindev#53]
Just followed the instructions, result:

[nodemon] starting `node src/server.js`
(node:11090) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11090) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:11090) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:11090) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
(node:11090) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:11090) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [cluster0-shard-00-02-4roep.mongodb.net:27017] on first connect [MongoError: bad auth : Authentication failed.

**Comment by franciscof5** [comment]
What the line 20 on backend/src/server.js

mongodb+srv://Mateus:Mateus@cluster0-4roep.mongodb.net/tindev?retryWrites=true&w=majority

**Comment by fariasmateuss** [comment]
Before running the server, you need to change the connection URL with mongodb.

**Comment by fariasmateuss** [comment]
Create a mongodb cluster and then change the database connection URL: 
https://github.com/fariasmateuss/tindev/blob/19b90e065b5c3d22f8969bdff859a3d639ccccbf/backend/src/server.js#L20
This will solve the problem.
